name: financialapp
description: A Application to Organize my Finances

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  extended_masked_text: ^2.1.0
  i18n_extension: ^4.0.0
  provider: ^5.0.0
  event_bus: ^2.0.0
  flutter_sticky_header: ^0.5.0
  get_storage: ^2.0.1
  flutter_colorpicker: ^0.4.0-nullsafety.0
  flutter_dotenv: ^4.0.0-nullsafety.0
  dio: ^4.0.0-beta7
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  carousel_slider: ^4.0.0-nullsafety.0
  recase: ^4.0.0-nullsafety.0
  flutter_form_builder:
    git: https://github.com/Sportner/flutter_form_builder.git

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - .env
  fonts:
    - family: Gibson
      fonts:
        - asset: assets/fonts/Gibson-Regular.ttf
        - asset: assets/fonts/Gibson-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Gibson-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gibson-BoldItalic.ttf
          style: italic
          weight: 700
